/**
 * Niche / language / location taxonomy used by the Search Strategy Engine.
 * Adding a niche here improves recall (synonyms, local-language terms, OSM tags,
 * provider category hints). Unknown niches still work through generic generation.
 */

export type Lang = 'en' | 'pl' | 'de' | 'cs' | 'sk' | 'uk' | 'ru' | 'es' | 'fr' | 'it' | 'pt' | 'nl';

export interface NicheDef {
  key: string;
  label: string;
  /** Industry name per language for client-facing text (English uses `label`). */
  labels?: Partial<Record<Lang, string>>;
  /** Synonyms per language (first = most common). */
  terms: Partial<Record<Lang, string[]>>;
  /** Specialty/sub-niche terms that increase recall (e.g. "implant dentist"). */
  specialties?: Partial<Record<Lang, string[]>>;
  /** OpenStreetMap tag filters (any match). */
  osm?: Array<[string, string]>;
  /** Google Places (New) `includedType`. */
  googleType?: string;
  /** Yelp category alias. */
  yelpCategory?: string;
  businessModel: 'local_service' | 'healthcare' | 'hospitality' | 'professional_services' | 'retail' | 'ecommerce' | 'b2b';
  /** Premium-segment keywords seen in names/categories (commercial relevance hint). */
  premiumHints?: string[];
}

export const NICHES: NicheDef[] = [
  {
    key: 'dentist',
    label: 'Dental clinics',
    labels: { pl: 'stomatologia', ru: 'стоматология', uk: 'стоматологія', de: 'Zahnmedizin' },
    businessModel: 'healthcare',
    osm: [['amenity', 'dentist'], ['healthcare', 'dentist']],
    googleType: 'dentist',
    yelpCategory: 'dentists',
    premiumHints: ['implant', 'aesthetic', 'estetyczn', 'cosmetic', 'premium', 'clinic', 'klinika', 'center', 'centrum'],
    terms: {
      en: ['dentist', 'dental clinic', 'dentistry', 'dental practice'],
      pl: ['dentysta', 'stomatolog', 'gabinet stomatologiczny', 'klinika stomatologiczna', 'stomatologia'],
      de: ['Zahnarzt', 'Zahnarztpraxis', 'Zahnklinik'],
      cs: ['zubař', 'zubní ordinace', 'stomatologie', 'zubní klinika'],
      sk: ['zubár', 'zubná ambulancia', 'stomatológia'],
      uk: ['стоматолог', 'стоматологія', 'стоматологічна клініка'],
      ru: ['стоматолог', 'стоматология', 'стоматологическая клиника'],
      es: ['dentista', 'clínica dental'],
      fr: ['dentiste', 'cabinet dentaire', 'centre dentaire'],
      it: ['dentista', 'studio dentistico'],
      pt: ['dentista', 'clínica dentária'],
      nl: ['tandarts', 'tandartspraktijk'],
    },
    specialties: {
      en: ['cosmetic dentistry', 'dental implants', 'orthodontist', 'pediatric dentist', 'teeth whitening', 'private dentist'],
      pl: ['stomatologia estetyczna', 'implanty zębów', 'ortodonta', 'stomatolog dziecięcy', 'implantologia', 'prywatny dentysta'],
      de: ['ästhetische Zahnmedizin', 'Zahnimplantate', 'Kieferorthopäde', 'Kinderzahnarzt'],
      cs: ['estetická stomatologie', 'zubní implantáty', 'ortodontista'],
      uk: ['естетична стоматологія', 'імплантація зубів', 'ортодонт'],
      ru: ['эстетическая стоматология', 'имплантация зубов', 'ортодонт'],
      es: ['odontología estética', 'implantes dentales', 'ortodoncista'],
      fr: ['dentisterie esthétique', 'implants dentaires', 'orthodontiste'],
      it: ['odontoiatria estetica', 'impianti dentali', 'ortodontista'],
    },
  },
  {
    key: 'restaurant',
    label: 'Restaurants',
    labels: { pl: 'gastronomia', ru: 'ресторанный бизнес', uk: 'ресторанний бізнес', de: 'Gastronomie' },
    businessModel: 'hospitality',
    osm: [['amenity', 'restaurant']],
    googleType: 'restaurant',
    yelpCategory: 'restaurants',
    premiumHints: ['fine dining', 'steak', 'wine', 'chef', 'sushi', 'omakase', 'gourmet'],
    terms: {
      en: ['restaurant', 'bistro', 'eatery'],
      pl: ['restauracja', 'bistro'],
      de: ['Restaurant', 'Gaststätte'],
      cs: ['restaurace', 'bistro'],
      sk: ['reštaurácia'],
      uk: ['ресторан'],
      ru: ['ресторан'],
      es: ['restaurante'],
      fr: ['restaurant', 'bistrot'],
      it: ['ristorante', 'trattoria'],
      pt: ['restaurante'],
      nl: ['restaurant'],
    },
    specialties: {
      en: ['fine dining restaurant', 'italian restaurant', 'sushi restaurant', 'steakhouse', 'wine bar'],
      pl: ['restauracja włoska', 'sushi', 'steakhouse', 'restauracja fine dining'],
      de: ['italienisches Restaurant', 'Sushi Restaurant', 'Steakhaus'],
      cs: ['italská restaurace', 'sushi restaurace', 'steakhouse'],
    },
  },
  {
    key: 'cafe',
    label: 'Cafés',
    businessModel: 'hospitality',
    osm: [['amenity', 'cafe']],
    googleType: 'cafe',
    yelpCategory: 'cafes',
    terms: {
      en: ['cafe', 'coffee shop'],
      pl: ['kawiarnia'],
      de: ['Café', 'Kaffeehaus'],
      cs: ['kavárna'],
      uk: ['кав’ярня', 'кавʼярня'],
      ru: ['кофейня', 'кафе'],
      es: ['cafetería'],
      fr: ['café'],
      it: ['caffetteria', 'bar caffè'],
    },
  },
  {
    key: 'law_firm',
    label: 'Law firms',
    labels: { pl: 'usługi prawne', ru: 'юридические услуги', uk: 'юридичні послуги', de: 'Rechtsberatung' },
    businessModel: 'professional_services',
    osm: [['office', 'lawyer']],
    googleType: 'lawyer',
    yelpCategory: 'lawyers',
    premiumHints: ['partners', 'legal', 'kancelaria', 'group'],
    terms: {
      en: ['law firm', 'lawyer', 'attorney', 'legal services'],
      pl: ['kancelaria prawna', 'adwokat', 'radca prawny', 'kancelaria adwokacka'],
      de: ['Rechtsanwalt', 'Anwaltskanzlei', 'Kanzlei'],
      cs: ['advokátní kancelář', 'advokát', 'právník'],
      sk: ['advokátska kancelária', 'advokát'],
      uk: ['юридична фірма', 'адвокат', 'юрист'],
      ru: ['юридическая фирма', 'адвокат', 'юрист'],
      es: ['abogado', 'bufete de abogados'],
      fr: ['avocat', "cabinet d'avocats"],
      it: ['avvocato', 'studio legale'],
    },
    specialties: {
      en: ['family lawyer', 'corporate lawyer', 'immigration lawyer', 'real estate lawyer'],
      pl: ['prawnik rodzinny', 'prawo gospodarcze', 'adwokat rozwodowy', 'prawo nieruchomości'],
      de: ['Familienrecht Anwalt', 'Wirtschaftskanzlei', 'Arbeitsrecht Anwalt'],
    },
  },
  {
    key: 'real_estate',
    label: 'Real estate agencies',
    labels: { pl: 'nieruchomości', ru: 'недвижимость', uk: 'нерухомість', de: 'Immobilien' },
    businessModel: 'professional_services',
    osm: [['office', 'estate_agent']],
    googleType: 'real_estate_agency',
    yelpCategory: 'realestateagents',
    premiumHints: ['luxury', 'premium', 'prestige', 'apartamenty', 'exclusive'],
    terms: {
      en: ['real estate agency', 'real estate agent', 'realtor', 'property agency'],
      pl: ['biuro nieruchomości', 'agencja nieruchomości', 'pośrednik nieruchomości'],
      de: ['Immobilienmakler', 'Immobilienbüro'],
      cs: ['realitní kancelář', 'realitní makléř'],
      sk: ['realitná kancelária'],
      uk: ['агентство нерухомості', 'рієлтор'],
      ru: ['агентство недвижимости', 'риэлтор'],
      es: ['inmobiliaria', 'agencia inmobiliaria'],
      fr: ['agence immobilière'],
      it: ['agenzia immobiliare'],
    },
    specialties: {
      en: ['luxury real estate', 'property management', 'commercial real estate'],
      pl: ['nieruchomości premium', 'zarządzanie najmem', 'nieruchomości komercyjne'],
    },
  },
  {
    key: 'beauty_salon',
    label: 'Beauty & aesthetic clinics',
    labels: { pl: 'kosmetologia', ru: 'индустрия красоты', uk: 'індустрія краси', de: 'Kosmetik' },
    businessModel: 'local_service',
    osm: [['shop', 'beauty']],
    googleType: 'beauty_salon',
    yelpCategory: 'beautysvc',
    premiumHints: ['aesthetic', 'estetyczn', 'clinic', 'klinika', 'medi', 'laser', 'spa'],
    terms: {
      en: ['beauty salon', 'beauty clinic', 'cosmetologist'],
      pl: ['salon kosmetyczny', 'gabinet kosmetyczny', 'kosmetolog', 'salon urody'],
      de: ['Kosmetikstudio', 'Schönheitssalon'],
      cs: ['kosmetický salon', 'kosmetika'],
      uk: ['салон краси', 'косметолог'],
      ru: ['салон красоты', 'косметолог'],
      es: ['salón de belleza', 'centro de estética'],
      fr: ['institut de beauté', 'esthéticienne'],
      it: ['centro estetico'],
    },
    specialties: {
      en: ['aesthetic medicine clinic', 'laser hair removal', 'medical spa'],
      pl: ['medycyna estetyczna', 'klinika medycyny estetycznej', 'depilacja laserowa'],
      de: ['ästhetische Medizin', 'Laser Haarentfernung'],
      cs: ['estetická medicína'],
      uk: ['естетична медицина'],
      ru: ['эстетическая медицина'],
    },
  },
  {
    key: 'hair_salon',
    label: 'Hair salons & barbers',
    labels: { pl: 'fryzjerstwo', ru: 'парикмахерские услуги', uk: 'перукарські послуги', de: 'Friseurhandwerk' },
    businessModel: 'local_service',
    osm: [['shop', 'hairdresser']],
    googleType: 'hair_salon',
    yelpCategory: 'hair',
    terms: {
      en: ['hair salon', 'hairdresser', 'barber shop'],
      pl: ['fryzjer', 'salon fryzjerski', 'barber'],
      de: ['Friseur', 'Friseursalon', 'Barbershop'],
      cs: ['kadeřnictví', 'barbershop'],
      uk: ['перукарня', 'барбершоп'],
      ru: ['парикмахерская', 'барбершоп'],
      es: ['peluquería', 'barbería'],
      fr: ['salon de coiffure', 'barbier'],
      it: ['parrucchiere', 'barbiere'],
    },
  },
  {
    key: 'gym',
    label: 'Gyms & fitness studios',
    labels: { pl: 'fitness', ru: 'фитнес', uk: 'фітнес', de: 'Fitness' },
    businessModel: 'local_service',
    osm: [['leisure', 'fitness_centre']],
    googleType: 'gym',
    yelpCategory: 'gyms',
    terms: {
      en: ['gym', 'fitness club', 'fitness studio'],
      pl: ['siłownia', 'klub fitness', 'studio fitness'],
      de: ['Fitnessstudio'],
      cs: ['posilovna', 'fitness centrum'],
      uk: ['спортзал', 'фітнес клуб'],
      ru: ['спортзал', 'фитнес клуб'],
      es: ['gimnasio'],
      fr: ['salle de sport'],
      it: ['palestra'],
    },
    specialties: {
      en: ['personal trainer', 'yoga studio', 'pilates studio', 'crossfit'],
      pl: ['trener personalny', 'studio jogi', 'pilates', 'crossfit'],
      de: ['Personal Trainer', 'Yogastudio', 'Pilates Studio'],
    },
  },
  {
    key: 'hotel',
    label: 'Hotels & guest houses',
    labels: { pl: 'hotelarstwo', ru: 'гостиничный бизнес', uk: 'готельний бізнес', de: 'Hotellerie' },
    businessModel: 'hospitality',
    osm: [['tourism', 'hotel'], ['tourism', 'guest_house']],
    googleType: 'hotel',
    yelpCategory: 'hotels',
    premiumHints: ['boutique', 'luxury', 'spa', 'resort', 'premium'],
    terms: {
      en: ['hotel', 'boutique hotel', 'guest house'],
      pl: ['hotel', 'pensjonat', 'apartamenty'],
      de: ['Hotel', 'Pension'],
      cs: ['hotel', 'penzion'],
      uk: ['готель'],
      ru: ['гостиница', 'отель'],
      es: ['hotel'],
      fr: ['hôtel'],
      it: ['hotel', 'albergo'],
    },
  },
  {
    key: 'medical_clinic',
    label: 'Medical clinics',
    labels: { pl: 'medycyna', ru: 'медицина', uk: 'медицина', de: 'Medizin' },
    businessModel: 'healthcare',
    osm: [['amenity', 'clinic'], ['amenity', 'doctors']],
    googleType: 'medical_clinic',
    yelpCategory: 'medcenters',
    premiumHints: ['premium', 'private', 'prywatn', 'centrum', 'center'],
    terms: {
      en: ['medical clinic', 'private clinic', 'medical center'],
      pl: ['przychodnia', 'klinika', 'centrum medyczne', 'prywatna klinika'],
      de: ['Arztpraxis', 'Klinik', 'Praxis'],
      cs: ['klinika', 'zdravotní středisko'],
      uk: ['медичний центр', 'клініка'],
      ru: ['медицинский центр', 'клиника'],
      es: ['clínica', 'centro médico'],
      fr: ['clinique', 'centre médical'],
      it: ['clinica', 'centro medico'],
    },
    specialties: {
      en: ['dermatologist', 'gynecologist', 'cardiologist', 'ophthalmologist'],
      pl: ['dermatolog', 'ginekolog', 'kardiolog', 'okulista'],
      de: ['Hautarzt', 'Frauenarzt', 'Kardiologe', 'Augenarzt'],
    },
  },
  {
    key: 'physiotherapy',
    label: 'Physiotherapy',
    labels: { pl: 'fizjoterapia', ru: 'физиотерапия', uk: 'фізіотерапія', de: 'Physiotherapie' },
    businessModel: 'healthcare',
    osm: [['healthcare', 'physiotherapist']],
    googleType: 'physiotherapist',
    yelpCategory: 'physicaltherapy',
    terms: {
      en: ['physiotherapist', 'physiotherapy clinic'],
      pl: ['fizjoterapeuta', 'fizjoterapia', 'rehabilitacja'],
      de: ['Physiotherapie', 'Physiotherapeut'],
      cs: ['fyzioterapie', 'fyzioterapeut'],
      uk: ['фізіотерапія', 'реабілітація'],
      ru: ['физиотерапия', 'реабилитация'],
      es: ['fisioterapia', 'fisioterapeuta'],
      fr: ['kinésithérapeute'],
      it: ['fisioterapia', 'fisioterapista'],
    },
  },
  {
    key: 'psychologist',
    label: 'Psychologists & therapists',
    businessModel: 'healthcare',
    osm: [['healthcare', 'psychotherapist']],
    yelpCategory: 'psychologists',
    terms: {
      en: ['psychologist', 'psychotherapist', 'therapy practice'],
      pl: ['psycholog', 'psychoterapeuta', 'gabinet psychologiczny'],
      de: ['Psychologe', 'Psychotherapeut'],
      cs: ['psycholog', 'psychoterapeut'],
      uk: ['психолог', 'психотерапевт'],
      ru: ['психолог', 'психотерапевт'],
      es: ['psicólogo'],
      fr: ['psychologue'],
      it: ['psicologo'],
    },
  },
  {
    key: 'veterinary',
    label: 'Veterinary clinics',
    labels: { pl: 'weterynaria', ru: 'ветеринария', uk: 'ветеринарія', de: 'Tiermedizin' },
    businessModel: 'healthcare',
    osm: [['amenity', 'veterinary']],
    googleType: 'veterinary_care',
    yelpCategory: 'vet',
    terms: {
      en: ['veterinary clinic', 'vet'],
      pl: ['weterynarz', 'lecznica weterynaryjna', 'przychodnia weterynaryjna'],
      de: ['Tierarzt', 'Tierklinik'],
      cs: ['veterinář', 'veterinární klinika'],
      uk: ['ветеринарна клініка', 'ветеринар'],
      ru: ['ветеринарная клиника', 'ветеринар'],
      es: ['veterinario', 'clínica veterinaria'],
      fr: ['vétérinaire'],
      it: ['veterinario'],
    },
  },
  {
    key: 'accounting',
    label: 'Accounting firms',
    labels: { pl: 'księgowość', ru: 'бухгалтерские услуги', uk: 'бухгалтерські послуги', de: 'Buchhaltung' },
    businessModel: 'professional_services',
    osm: [['office', 'accountant'], ['office', 'tax_advisor']],
    googleType: 'accounting',
    yelpCategory: 'accountants',
    terms: {
      en: ['accounting firm', 'accountant', 'bookkeeping'],
      pl: ['biuro rachunkowe', 'księgowa', 'usługi księgowe'],
      de: ['Steuerberater', 'Buchhaltung'],
      cs: ['účetní kancelář', 'účetnictví'],
      uk: ['бухгалтерські послуги'],
      ru: ['бухгалтерские услуги'],
      es: ['asesoría contable', 'gestoría'],
      fr: ['expert-comptable'],
      it: ['commercialista'],
    },
  },
  {
    key: 'architect',
    label: 'Architects & interior designers',
    businessModel: 'professional_services',
    osm: [['office', 'architect']],
    yelpCategory: 'architects',
    premiumHints: ['studio', 'design', 'interior'],
    terms: {
      en: ['architecture firm', 'architect', 'interior designer'],
      pl: ['biuro architektoniczne', 'architekt', 'projektowanie wnętrz', 'architekt wnętrz'],
      de: ['Architekturbüro', 'Architekt', 'Innenarchitekt'],
      cs: ['architektonická kancelář', 'architekt', 'interiérový design'],
      uk: ['архітектурне бюро', 'дизайн інтер’єру'],
      ru: ['архитектурное бюро', 'дизайн интерьера'],
      es: ['estudio de arquitectura', 'interiorista'],
      fr: ["cabinet d'architecture", "architecte d'intérieur"],
      it: ['studio di architettura', 'interior designer'],
    },
  },
  {
    key: 'construction',
    label: 'Construction & renovation',
    labels: { pl: 'budownictwo', ru: 'строительство', uk: 'будівництво', de: 'Bauwesen' },
    businessModel: 'local_service',
    osm: [['office', 'construction_company'], ['craft', 'builder']],
    googleType: 'general_contractor',
    yelpCategory: 'contractors',
    terms: {
      en: ['construction company', 'general contractor', 'renovation company'],
      pl: ['firma budowlana', 'remonty', 'wykończenia wnętrz'],
      de: ['Bauunternehmen', 'Renovierung', 'Sanierung'],
      cs: ['stavební firma', 'rekonstrukce'],
      uk: ['будівельна компанія', 'ремонт квартир'],
      ru: ['строительная компания', 'ремонт квартир'],
      es: ['empresa de construcción', 'reformas'],
      fr: ['entreprise de construction', 'rénovation'],
      it: ['impresa edile', 'ristrutturazioni'],
    },
  },
  {
    key: 'car_repair',
    label: 'Car repair shops',
    labels: { pl: 'motoryzacja', ru: 'автосервис', uk: 'автосервіс', de: 'Kfz-Service' },
    businessModel: 'local_service',
    osm: [['shop', 'car_repair']],
    googleType: 'car_repair',
    yelpCategory: 'autorepair',
    terms: {
      en: ['car repair', 'auto repair shop', 'car service'],
      pl: ['warsztat samochodowy', 'mechanik', 'serwis samochodowy'],
      de: ['Autowerkstatt', 'KFZ Werkstatt'],
      cs: ['autoservis'],
      uk: ['автосервіс', 'СТО'],
      ru: ['автосервис', 'СТО'],
      es: ['taller mecánico'],
      fr: ['garage automobile'],
      it: ['officina meccanica'],
    },
  },
  {
    key: 'car_dealer',
    label: 'Car dealers',
    businessModel: 'retail',
    osm: [['shop', 'car']],
    googleType: 'car_dealer',
    yelpCategory: 'car_dealers',
    terms: {
      en: ['car dealer', 'car dealership'],
      pl: ['salon samochodowy', 'komis samochodowy', 'dealer samochodowy'],
      de: ['Autohaus', 'Autohändler'],
      cs: ['autosalon', 'autobazar'],
      uk: ['автосалон'],
      ru: ['автосалон'],
      es: ['concesionario'],
      fr: ['concessionnaire automobile'],
      it: ['concessionaria auto'],
    },
  },
  {
    key: 'florist',
    label: 'Florists',
    businessModel: 'retail',
    osm: [['shop', 'florist']],
    googleType: 'florist',
    yelpCategory: 'florists',
    terms: {
      en: ['florist', 'flower shop'],
      pl: ['kwiaciarnia'],
      de: ['Blumenladen', 'Florist'],
      cs: ['květinářství'],
      uk: ['квітковий магазин'],
      ru: ['цветочный магазин'],
      es: ['floristería'],
      fr: ['fleuriste'],
      it: ['fioraio'],
    },
  },
  {
    key: 'bakery',
    label: 'Bakeries & patisseries',
    businessModel: 'retail',
    osm: [['shop', 'bakery'], ['shop', 'pastry']],
    googleType: 'bakery',
    yelpCategory: 'bakeries',
    terms: {
      en: ['bakery', 'patisserie'],
      pl: ['piekarnia', 'cukiernia'],
      de: ['Bäckerei', 'Konditorei'],
      cs: ['pekárna', 'cukrárna'],
      uk: ['пекарня', 'кондитерська'],
      ru: ['пекарня', 'кондитерская'],
      es: ['panadería', 'pastelería'],
      fr: ['boulangerie', 'pâtisserie'],
      it: ['panetteria', 'pasticceria'],
    },
  },
  {
    key: 'photographer',
    label: 'Photographers',
    businessModel: 'local_service',
    osm: [['craft', 'photographer'], ['shop', 'photo']],
    yelpCategory: 'photographers',
    terms: {
      en: ['photographer', 'photo studio'],
      pl: ['fotograf', 'studio fotograficzne'],
      de: ['Fotograf', 'Fotostudio'],
      cs: ['fotograf', 'fotoateliér'],
      uk: ['фотограф', 'фотостудія'],
      ru: ['фотограф', 'фотостудия'],
      es: ['fotógrafo', 'estudio fotográfico'],
      fr: ['photographe'],
      it: ['fotografo'],
    },
    specialties: { en: ['wedding photographer'], pl: ['fotograf ślubny'], de: ['Hochzeitsfotograf'] },
  },
  {
    key: 'wedding',
    label: 'Wedding venues & planners',
    businessModel: 'hospitality',
    terms: {
      en: ['wedding venue', 'wedding planner'],
      pl: ['sala weselna', 'organizator ślubów', 'dom weselny'],
      de: ['Hochzeitslocation', 'Hochzeitsplaner'],
      cs: ['svatební místo', 'svatební agentura'],
      uk: ['весільний організатор'],
      ru: ['свадебный организатор', 'банкетный зал'],
      es: ['lugar para bodas', 'organizador de bodas'],
      fr: ['salle de mariage', 'organisateur de mariage'],
      it: ['location matrimoni', 'wedding planner'],
    },
  },
  {
    key: 'language_school',
    label: 'Language schools',
    businessModel: 'local_service',
    osm: [['amenity', 'language_school']],
    yelpCategory: 'language_schools',
    terms: {
      en: ['language school', 'english school'],
      pl: ['szkoła językowa', 'kursy językowe'],
      de: ['Sprachschule'],
      cs: ['jazyková škola'],
      uk: ['мовна школа', 'курси англійської'],
      ru: ['языковая школа', 'курсы английского'],
      es: ['academia de idiomas'],
      fr: ['école de langues'],
      it: ['scuola di lingue'],
    },
  },
  {
    key: 'optician',
    label: 'Opticians',
    businessModel: 'retail',
    osm: [['shop', 'optician']],
    yelpCategory: 'opticians',
    terms: {
      en: ['optician', 'eyewear store'],
      pl: ['optyk', 'salon optyczny'],
      de: ['Optiker'],
      cs: ['optika', 'oční optika'],
      uk: ['оптика'],
      ru: ['оптика'],
      es: ['óptica'],
      fr: ['opticien'],
      it: ['ottico'],
    },
  },
  {
    key: 'furniture',
    label: 'Furniture makers & stores',
    businessModel: 'retail',
    osm: [['shop', 'furniture'], ['craft', 'carpenter']],
    googleType: 'furniture_store',
    yelpCategory: 'furniture',
    terms: {
      en: ['furniture store', 'custom furniture'],
      pl: ['sklep meblowy', 'meble na wymiar', 'stolarz'],
      de: ['Möbelhaus', 'Möbel nach Maß', 'Tischlerei'],
      cs: ['nábytek', 'nábytek na míru', 'truhlářství'],
      uk: ['меблі на замовлення'],
      ru: ['мебель на заказ'],
      es: ['tienda de muebles', 'muebles a medida'],
      fr: ['magasin de meubles', 'meubles sur mesure'],
      it: ['negozio di mobili', 'mobili su misura'],
    },
  },
  {
    key: 'insurance',
    label: 'Insurance agencies',
    businessModel: 'professional_services',
    osm: [['office', 'insurance']],
    googleType: 'insurance_agency',
    yelpCategory: 'insurance',
    terms: {
      en: ['insurance agency', 'insurance broker'],
      pl: ['agencja ubezpieczeniowa', 'broker ubezpieczeniowy'],
      de: ['Versicherungsagentur', 'Versicherungsmakler'],
      cs: ['pojišťovací makléř', 'pojišťovna'],
      uk: ['страхова агенція'],
      ru: ['страховое агентство'],
      es: ['agencia de seguros', 'corredor de seguros'],
      fr: ["agence d'assurance", 'courtier en assurance'],
      it: ['agenzia assicurativa'],
    },
  },
  {
    key: 'plumber',
    label: 'Plumbers & HVAC',
    businessModel: 'local_service',
    osm: [['craft', 'plumber'], ['craft', 'hvac']],
    googleType: 'plumber',
    yelpCategory: 'plumbing',
    terms: {
      en: ['plumber', 'plumbing services', 'HVAC'],
      pl: ['hydraulik', 'instalacje sanitarne', 'klimatyzacja'],
      de: ['Klempner', 'Sanitär', 'Heizung Sanitär'],
      cs: ['instalatér', 'topenář'],
      uk: ['сантехнік'],
      ru: ['сантехник'],
      es: ['fontanero'],
      fr: ['plombier'],
      it: ['idraulico'],
    },
  },
  {
    key: 'electrician',
    label: 'Electricians',
    businessModel: 'local_service',
    osm: [['craft', 'electrician']],
    googleType: 'electrician',
    yelpCategory: 'electricians',
    terms: {
      en: ['electrician', 'electrical services'],
      pl: ['elektryk', 'usługi elektryczne'],
      de: ['Elektriker', 'Elektroinstallation'],
      cs: ['elektrikář'],
      uk: ['електрик'],
      ru: ['электрик'],
      es: ['electricista'],
      fr: ['électricien'],
      it: ['elettricista'],
    },
  },
  {
    key: 'spa',
    label: 'Spa & massage',
    businessModel: 'local_service',
    osm: [['shop', 'massage'], ['leisure', 'spa']],
    googleType: 'spa',
    yelpCategory: 'spas',
    terms: {
      en: ['spa', 'massage salon', 'day spa'],
      pl: ['spa', 'salon masażu', 'masaż'],
      de: ['Massagepraxis', 'Day Spa'],
      cs: ['masáže', 'wellness'],
      uk: ['спа салон', 'масаж'],
      ru: ['спа салон', 'массаж'],
      es: ['spa', 'centro de masajes'],
      fr: ['spa', 'institut de massage'],
      it: ['spa', 'centro massaggi'],
    },
  },
  {
    key: 'travel_agency',
    label: 'Travel agencies',
    businessModel: 'retail',
    osm: [['shop', 'travel_agency']],
    googleType: 'travel_agency',
    yelpCategory: 'travelagents',
    terms: {
      en: ['travel agency'],
      pl: ['biuro podróży'],
      de: ['Reisebüro'],
      cs: ['cestovní kancelář'],
      uk: ['туристична агенція'],
      ru: ['туристическое агентство', 'турагентство'],
      es: ['agencia de viajes'],
      fr: ['agence de voyages'],
      it: ['agenzia di viaggi'],
    },
  },
  {
    key: 'jewelry',
    label: 'Jewellers',
    businessModel: 'retail',
    osm: [['shop', 'jewelry']],
    googleType: 'jewelry_store',
    yelpCategory: 'jewelry',
    premiumHints: ['atelier', 'luxury', 'diamond', 'gold'],
    terms: {
      en: ['jewelry store', 'jeweler'],
      pl: ['jubiler', 'pracownia złotnicza'],
      de: ['Juwelier', 'Goldschmied'],
      cs: ['klenotnictví', 'zlatnictví'],
      uk: ['ювелірний магазин'],
      ru: ['ювелирный магазин'],
      es: ['joyería'],
      fr: ['bijouterie'],
      it: ['gioielleria'],
    },
  },
  {
    key: 'clothing',
    label: 'Fashion boutiques',
    businessModel: 'retail',
    osm: [['shop', 'clothes'], ['shop', 'boutique']],
    googleType: 'clothing_store',
    yelpCategory: 'fashion',
    terms: {
      en: ['clothing boutique', 'fashion boutique'],
      pl: ['butik', 'sklep odzieżowy'],
      de: ['Boutique', 'Modegeschäft'],
      cs: ['butik', 'obchod s oblečením'],
      uk: ['бутик одягу'],
      ru: ['бутик одежды'],
      es: ['boutique de ropa'],
      fr: ['boutique de vêtements'],
      it: ['boutique abbigliamento'],
    },
  },
  {
    key: 'marketing_agency',
    label: 'Marketing agencies',
    businessModel: 'b2b',
    osm: [['office', 'advertising_agency']],
    yelpCategory: 'marketing',
    terms: {
      en: ['marketing agency', 'advertising agency'],
      pl: ['agencja marketingowa', 'agencja reklamowa'],
      de: ['Marketingagentur', 'Werbeagentur'],
      cs: ['marketingová agentura', 'reklamní agentura'],
      uk: ['маркетингова агенція'],
      ru: ['маркетинговое агентство', 'рекламное агентство'],
      es: ['agencia de marketing'],
      fr: ['agence marketing'],
      it: ['agenzia di marketing'],
    },
  },
  {
    key: 'it_company',
    label: 'IT & software companies',
    businessModel: 'b2b',
    osm: [['office', 'it']],
    terms: {
      en: ['software company', 'IT company', 'software house'],
      pl: ['software house', 'firma IT', 'firma informatyczna'],
      de: ['Softwareentwicklung', 'IT-Dienstleister'],
      cs: ['softwarová firma', 'IT firma'],
      uk: ['IT компанія'],
      ru: ['IT компания'],
      es: ['empresa de software'],
      fr: ['entreprise informatique'],
      it: ['azienda software'],
    },
  },
];

/** Country (ISO-2) → languages to search in (first = primary local language). */
export const COUNTRY_LANGUAGES: Record<string, Lang[]> = {
  PL: ['pl', 'en'],
  DE: ['de', 'en'],
  AT: ['de', 'en'],
  CH: ['de', 'fr', 'it', 'en'],
  CZ: ['cs', 'en'],
  SK: ['sk', 'cs', 'en'],
  UA: ['uk', 'ru', 'en'],
  RU: ['ru', 'en'],
  BY: ['ru', 'en'],
  KZ: ['ru', 'en'],
  ES: ['es', 'en'],
  FR: ['fr', 'en'],
  BE: ['fr', 'nl', 'en'],
  NL: ['nl', 'en'],
  LU: ['fr', 'de', 'en'],
  IT: ['it', 'en'],
  PT: ['pt', 'en'],
  GB: ['en'],
  IE: ['en'],
  US: ['en', 'es'],
  CA: ['en', 'fr'],
  AU: ['en'],
  NZ: ['en'],
  AE: ['en'],
  LT: ['en', 'ru'],
  LV: ['en', 'ru'],
  EE: ['en', 'ru'],
  CY: ['en'],
  MT: ['en'],
};

/** Localised city names (improves local-language queries). Keys are lower-case, diacritic-free aliases. */
export const CITY_ALIASES: Array<{ names: Partial<Record<Lang, string>>; aliases: string[]; country: string; districts?: string[] }> = [
  {
    names: { en: 'Warsaw', pl: 'Warszawa', de: 'Warschau', uk: 'Варшава', ru: 'Варшава', cs: 'Varšava', fr: 'Varsovie', es: 'Varsovia', it: 'Varsavia' },
    aliases: ['warsaw', 'warszawa', 'варшава', 'warschau', 'varsovie', 'varsovia', 'varsavia', 'varsava'],
    country: 'PL',
    districts: ['Śródmieście', 'Mokotów', 'Wola', 'Ochota', 'Żoliborz', 'Praga-Południe', 'Praga-Północ', 'Ursynów', 'Wilanów', 'Bielany', 'Bemowo', 'Targówek', 'Białołęka', 'Wawer', 'Włochy', 'Ursus', 'Wesoła', 'Rembertów'],
  },
  {
    names: { en: 'Krakow', pl: 'Kraków', de: 'Krakau', uk: 'Краків', ru: 'Краков', cs: 'Krakov' },
    aliases: ['krakow', 'cracow', 'krakau', 'краков', 'краків', 'krakov'],
    country: 'PL',
    districts: ['Stare Miasto', 'Kazimierz', 'Podgórze', 'Krowodrza', 'Prądnik Biały', 'Prądnik Czerwony', 'Dębniki', 'Nowa Huta', 'Bronowice', 'Zwierzyniec', 'Grzegórzki', 'Czyżyny', 'Bieżanów-Prokocim', 'Łagiewniki', 'Podgórze Duchackie'],
  },
  { names: { en: 'Wroclaw', pl: 'Wrocław', de: 'Breslau', uk: 'Вроцлав', ru: 'Вроцлав' }, aliases: ['wroclaw', 'breslau', 'вроцлав'], country: 'PL', districts: ['Stare Miasto', 'Śródmieście', 'Krzyki', 'Fabryczna', 'Psie Pole'] },
  { names: { en: 'Gdansk', pl: 'Gdańsk', de: 'Danzig', uk: 'Гданськ', ru: 'Гданьск' }, aliases: ['gdansk', 'danzig', 'гданьск', 'гданськ'], country: 'PL' },
  { names: { en: 'Poznan', pl: 'Poznań', de: 'Posen', uk: 'Познань', ru: 'Познань' }, aliases: ['poznan', 'posen', 'познань'], country: 'PL' },
  { names: { en: 'Lodz', pl: 'Łódź', uk: 'Лодзь', ru: 'Лодзь' }, aliases: ['lodz', 'лодзь'], country: 'PL' },
  {
    names: { en: 'Prague', cs: 'Praha', de: 'Prag', uk: 'Прага', ru: 'Прага', pl: 'Praga' },
    aliases: ['prague', 'praha', 'prag', 'прага', 'praga'],
    country: 'CZ',
    districts: ['Praha 1', 'Praha 2', 'Praha 3', 'Praha 4', 'Praha 5', 'Praha 6', 'Praha 7', 'Praha 8', 'Praha 9', 'Praha 10'],
  },
  { names: { en: 'Brno', cs: 'Brno', ru: 'Брно' }, aliases: ['brno', 'брно'], country: 'CZ' },
  {
    names: { en: 'Berlin', de: 'Berlin', uk: 'Берлін', ru: 'Берлин', pl: 'Berlin' },
    aliases: ['berlin', 'берлин', 'берлін'],
    country: 'DE',
    districts: ['Mitte', 'Friedrichshain-Kreuzberg', 'Pankow', 'Charlottenburg-Wilmersdorf', 'Spandau', 'Steglitz-Zehlendorf', 'Tempelhof-Schöneberg', 'Neukölln', 'Treptow-Köpenick', 'Marzahn-Hellersdorf', 'Lichtenberg', 'Reinickendorf'],
  },
  { names: { en: 'Munich', de: 'München', uk: 'Мюнхен', ru: 'Мюнхен', pl: 'Monachium' }, aliases: ['munich', 'munchen', 'muenchen', 'мюнхен', 'monachium'], country: 'DE' },
  { names: { en: 'Vienna', de: 'Wien', uk: 'Відень', ru: 'Вена', pl: 'Wiedeń' }, aliases: ['vienna', 'wien', 'вена', 'відень', 'wieden'], country: 'AT' },
  { names: { en: 'Kyiv', uk: 'Київ', ru: 'Киев', pl: 'Kijów' }, aliases: ['kyiv', 'kiev', 'київ', 'киев', 'kijow'], country: 'UA' },
  { names: { en: 'Lviv', uk: 'Львів', ru: 'Львов', pl: 'Lwów' }, aliases: ['lviv', 'lvov', 'львів', 'львов', 'lwow'], country: 'UA' },
  { names: { en: 'London' }, aliases: ['london', 'лондон', 'londyn'], country: 'GB' },
  { names: { en: 'Madrid', es: 'Madrid' }, aliases: ['madrid', 'мадрид'], country: 'ES' },
  { names: { en: 'Barcelona', es: 'Barcelona' }, aliases: ['barcelona', 'барселона'], country: 'ES' },
  { names: { en: 'Paris', fr: 'Paris' }, aliases: ['paris', 'париж', 'paryz'], country: 'FR' },
  { names: { en: 'Milan', it: 'Milano' }, aliases: ['milan', 'milano', 'милан', 'mediolan'], country: 'IT' },
  { names: { en: 'Rome', it: 'Roma' }, aliases: ['rome', 'roma', 'рим', 'rzym'], country: 'IT' },
  { names: { en: 'Lisbon', pt: 'Lisboa' }, aliases: ['lisbon', 'lisboa', 'лиссабон', 'lizbona'], country: 'PT' },
  { names: { en: 'Amsterdam', nl: 'Amsterdam' }, aliases: ['amsterdam', 'амстердам'], country: 'NL' },
  { names: { en: 'Bratislava', sk: 'Bratislava' }, aliases: ['bratislava', 'братислава'], country: 'SK' },
];
